name: Wattable Blog
favicon: null
layout_spectrum: 0.57984
typography_spectrum: 0.37824
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#818286'
    - '#27aae2'
    - '#fcb040'
    - '#f25a29'
  brandStrength: 1
  lightness: 1
  saturation: 0.6875
  rhythmicContrast: 0.9378716247156262
purpose: []
