name: Wattable Blog
favicon: null
layout_spectrum: 0.8467095512896776
typography_spectrum: 0.11893418175168335
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.4867974645458162
  lightness: 0.782292133430019
  saturation: 0.779307592427358
  rhythmicContrast: 0.9378716247156262
purpose: []
